ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ app.ApplicationKt.module ]
    }
    hedra {
        apiKey = ${?HEDRA_API_KEY}
    }
    elevenlabs {
        apiKey = ${?ELEVENLABS_API_KEY}
    }
    veo3 {
        apiKey = ${?VEO3_API_KEY}
    }
    anthropic {
        apiKey = ${?ANTHROPIC_API_KEY}
    }
    jwt {
        secret = ${?JWT_SECRET}
    }
    database {
        url = ${?DATABASE_URL}
        user = ${?DATABASE_USER}
        password = ${?DATABASE_PASSWORD}
    }
    rustore {
        apiKey = ${?RUSTORE_API_KEY}
    }
    google {
        serviceAccount = ${?GOOGLE_SERVICE_ACCOUNT_JSON}
    }
}
